POSTGRESQL_DBNAME = "jugglefit_website"
POSTGRESQL_USERNAME = "postgres"
POSTGRESQL_PASSWORD = "Password1!"
POSTGRESQL_HOST = "localhost"
POSTGRESQL_PORT = "5432"

SHORT_URL_EXPIRY_MONTHS = 3
SHORT_URL_REFRESH_DAYS = 7
SHORT_URL_EXTEND_MONTHS = 1
EXPIRED_URL_CLEANUP_INTERVAL = 7 * 24 * 60 * 60  # 7 days in seconds
