from pathlib import Path

PYLIB_ROOT = Path(__file__).parent.parent

MAX_TRICK_NAME_LENGTH = 100

# Props Count Constraints
MIN_TRICK_PROPS_COUNT = 1
MAX_TRICK_PROPS_COUNT = 9
DEFAULT_MIN_TRICK_PROPS_COUNT = 3
DEFAULT_MAX_TRICK_PROPS_COUNT = 9

# Difficulty Constraints
MIN_TRICK_DIFFICULTY = 0
MAX_TRICK_DIFFICULTY = 100
DEFAULT_MIN_TRICK_DIFFICULTY = 20
DEFAULT_MAX_TRICK_DIFFICULTY = 30